In [1]:
import numpy as np

In [2]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [3]:
np.save('myarray', arr)

In [4]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.load('myarray.npy')

array([0, 1, 2, 3, 4])

In [8]:
arr1 = np.load('myarray.npy')

In [9]:
arr2 = arr

In [10]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.savez('ziparray.npz', x=arr1, y=arr2)

In [12]:
archive_arr = np.load('ziparray.npz')

In [13]:
archive_arr

In [14]:
archive_arr['x']

array([0, 1, 2, 3, 4])

In [15]:
archive_arr['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.savetxt('mytextarray.txt', arr, delimiter=' ')