In [1]:
import numpy as np

In [3]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [11]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [12]:
A = np.random.randn(10)

A

array([-0.77232496,  0.24515759,  0.38935352,  0.49212932,  0.10632323,
       -1.87841746,  1.43004289, -0.66909192, -1.78483632,  1.33882072])

In [14]:
B = np.random.randn(10)
B

array([-0.78432679,  0.2379221 ,  0.51737749,  1.42533834,  0.43156811,
       -1.04781833, -0.70709242, -0.58530742,  0.012651  ,  1.56882731])

In [16]:
# Binary Functions
np.add(A,B)

array([-1.55665176,  0.48307968,  0.90673101,  1.91746766,  0.53789135,
       -2.92623579,  0.72295047, -1.25439934, -1.77218532,  2.90764803])

In [17]:
np.maximum(A, B)

array([-0.77232496,  0.24515759,  0.51737749,  1.42533834,  0.43156811,
       -1.04781833,  1.43004289, -0.58530742,  0.012651  ,  1.56882731])

In [18]:
np.minimum(A, B)

array([-0.78432679,  0.2379221 ,  0.38935352,  0.49212932,  0.10632323,
       -1.87841746, -0.70709242, -0.66909192, -1.78483632,  1.33882072])

In [19]:
website = "http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"
import webbrowser
webbrowser.open(website)

True